-- TB_CUST_PRODUCT에 개통일자(OPEN_DATE), 해지일자(CANCEL_DATE) 컬럼 추가

ALTER TABLE TB_CUST_PRODUCT
  ADD COLUMN IF NOT EXISTS OPEN_DATE DATE DEFAULT NULL COMMENT '개통일자',
  ADD COLUMN IF NOT EXISTS CANCEL_DATE DATE DEFAULT NULL COMMENT '해지일자';

-- IF NOT EXISTS 미지원 시:
-- ALTER TABLE TB_CUST_PRODUCT ADD COLUMN OPEN_DATE DATE DEFAULT NULL COMMENT '개통일자';
-- ALTER TABLE TB_CUST_PRODUCT ADD COLUMN CANCEL_DATE DATE DEFAULT NULL COMMENT '해지일자';
