-- TB_CUSTOMER: 접수일(RECEIPT_DT), 해약일(CANCELL_DT), 가입일자(JOIN_DATE) 컬럼 추가
-- 컬럼이 이미 있으면 오류가 나므로, 없을 때만 추가하는 형태로 실행하세요.

ALTER TABLE TB_CUSTOMER
  ADD COLUMN IF NOT EXISTS RECEIPT_DT DATE DEFAULT NULL COMMENT '접수일',
  ADD COLUMN IF NOT EXISTS CANCELL_DT DATE DEFAULT NULL COMMENT '해약일',
  ADD COLUMN IF NOT EXISTS JOIN_DATE DATE DEFAULT NULL COMMENT '가입일자';

-- IF NOT EXISTS 미지원 시 개별 실행:
-- ALTER TABLE TB_CUSTOMER ADD COLUMN RECEIPT_DT DATE DEFAULT NULL COMMENT '접수일';
-- ALTER TABLE TB_CUSTOMER ADD COLUMN CANCELL_DT DATE DEFAULT NULL COMMENT '해약일';
-- ALTER TABLE TB_CUSTOMER ADD COLUMN JOIN_DATE DATE DEFAULT NULL COMMENT '가입일자';
