-- TB_CUST_PRODUCT에 개통상태(OPEN_STATUS) 컬럼 추가
-- 고객:상품 1:M 관계이므로 개통상태는 상품 단위로 관리 (CUST_STATUS 공통코드 사용)
ALTER TABLE TB_CUST_PRODUCT
  ADD COLUMN IF NOT EXISTS OPEN_STATUS VARCHAR(20) DEFAULT 'RECEIPT' COMMENT '개통상태(접수, 진행중, 개통완료, 취소, 해지 등 - CUST_STATUS)';

-- 기존 데이터 보정: NULL이면 접수로 설정
-- UPDATE TB_CUST_PRODUCT SET OPEN_STATUS = 'RECEIPT' WHERE OPEN_STATUS IS NULL;
