-- 로그인/로그아웃 히스토리 테이블 (TB_USER_LOGIN_HISTORY)
-- 로그인·로그아웃 시 AuthService에서 INSERT (EVENT_TYPE = 'LOGIN' | 'LOGOUT')

DROP TABLE IF EXISTS `TB_USER_LOGIN_HISTORY`;

CREATE TABLE `TB_USER_LOGIN_HISTORY` (
  `HISTORY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL COMMENT '사용자 ID (TB_USER.USER_ID)',
  `EVENT_TYPE` varchar(20) NOT NULL COMMENT 'LOGIN | LOGOUT',
  `IP_ADDRESS` varchar(45) DEFAULT NULL COMMENT '클라이언트 IP',
  `USER_AGENT` varchar(500) DEFAULT NULL COMMENT 'User-Agent (선택)',
  `CREATED_AT` datetime DEFAULT current_timestamp() COMMENT '발생 시각',
  PRIMARY KEY (`HISTORY_ID`),
  KEY `IDX_LOGIN_HISTORY_USER_ID` (`USER_ID`),
  KEY `IDX_LOGIN_HISTORY_CREATED_AT` (`CREATED_AT`),
  CONSTRAINT `FK_LOGIN_HISTORY_USER` FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그인/로그아웃 이력';
