-- CUST_STATUS(진행 상태) 공통코드: CODE_VALUE 영문, CODE_NAME 한글
-- 실행: mysql -h 127.0.0.1 -P 3307 -u root -p1234 managesys < docs/insert-cust-status-codes.sql

INSERT IGNORE INTO TB_GROUP_CODE (GROUP_CODE, GROUP_NAME, USE_YN) VALUES ('CUST_STATUS', '진행 상태', 'Y');

INSERT INTO TB_COMMON_CODE (GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN) VALUES
  ('CUST_STATUS', 'RECEIPT', '접수', 1, 'Y'),
  ('CUST_STATUS', 'IN_PROGRESS', '진행중', 2, 'Y'),
  ('CUST_STATUS', 'COMPLETED', '개통완료', 3, 'Y'),
  ('CUST_STATUS', 'CANCELLED', '취소', 4, 'Y')
ON DUPLICATE KEY UPDATE
  CODE_NAME = VALUES(CODE_NAME),
  SORT_ORDER = VALUES(SORT_ORDER),
  USE_YN = VALUES(USE_YN),
  UPDATED_AT = CURRENT_TIMESTAMP;
